# Generated by Django 3.2.8 on 2021-11-10 11:58

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('gold_id', models.IntegerField(default=app.models.generate_gold_id, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ornament', models.CharField(max_length=100)),
                ('gross_weight', models.FloatField()),
                ('stone_weight', models.FloatField()),
                ('net_weight', models.FloatField()),
                ('purity', models.FloatField()),
                ('gold_price', models.FloatField()),
                ('gross_amount', models.FloatField()),
                ('margin', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('release_amount1', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('business_type', models.CharField(default='Release', max_length=100)),
                ('address', models.TextField()),
                ('address_pic', models.ImageField(upload_to='release/image/')),
                ('id_proof', models.ImageField(upload_to='release/id_proof/')),
                ('pledge_slip', models.ImageField(upload_to='release/slip/')),
                ('release_slip', models.ImageField(upload_to='release_slip/')),
                ('release_amount', models.ImageField(upload_to='release_amount/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.IntegerField(default=app.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('business_type', models.CharField(default='Physical', max_length=100)),
                ('address', models.TextField()),
                ('address_proof', models.ImageField(upload_to='customer/address_proof/')),
                ('id_proof', models.ImageField(upload_to='customer/id_proof/')),
                ('gross_weight', models.FloatField()),
                ('stone', models.FloatField(default=0)),
                ('net_weight', models.FloatField()),
                ('gold_price', models.IntegerField()),
                ('purity', models.IntegerField()),
                ('gross_amount', models.FloatField()),
                ('margin', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('releasing', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('customer_pic', models.ImageField(upload_to='customer/image/')),
                ('ornament_pic', models.ImageField(upload_to='ornament_pic/image/')),
                ('ornament_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Aproved', 'Aproved'), ('Reject', 'Reject')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
