# Generated by Django 3.2.8 on 2021-10-30 11:59

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.IntegerField(default=app.models.generate_id, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('gross_weight', models.FloatField()),
                ('stone', models.FloatField(default=0)),
                ('net_weight', models.FloatField()),
                ('gold_price', models.IntegerField()),
                ('purity', models.IntegerField()),
                ('gross_amount', models.FloatField()),
                ('margin', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('releasing', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('customer_pic', models.ImageField(blank=True, null=True, upload_to='customer/image')),
                ('ornament_pic', models.ImageField(blank=True, null=True, upload_to='ornament_pic/image')),
                ('ornament_type', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, choices=[('Aproved', 'Aproved'), ('Reject', 'Reject')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
