# Generated by Django 3.2.8 on 2021-10-20 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('aadhar_number', models.IntegerField()),
                ('aadhar_pic', models.ImageField(upload_to='aadhar/image')),
                ('address_proof', models.ImageField(blank=True, null=True, upload_to='address-proof')),
                ('live_pic', models.ImageField(upload_to='live-image')),
                ('release_slip', models.ImageField(upload_to='releasr-slip')),
                ('amount', models.FloatField()),
                ('gold_weight', models.CharField(max_length=10)),
                ('amount_options', models.CharField(max_length=50)),
                ('status', models.BooleanField(choices=[('Aproved', 'Aproved'), ('Reject', 'Reject')])),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
