# Generated by Django 3.2.8 on 2021-10-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='amount',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='aadhar_number',
            new_name='gold_price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='aadhar_pic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='amount_options',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gold_weight',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='live_pic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='release_slip',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(default=1, upload_to='customer/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='gross_amount',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='gross_weight',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='margin',
            field=models.FloatField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='net_amount',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='net_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='ornament_pic',
            field=models.ImageField(default=2, upload_to='ornament_pic/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='purity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='releasing',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='stone',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Aproved', 'Aproved'), ('Reject', 'Reject')], max_length=50),
        ),
    ]
