# Generated by Django 3.2.8 on 2021-11-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Aproved', 'Aproved'), ('Reject', 'Reject')], max_length=50),
        ),
    ]
