# Generated by Django 3.2.8 on 2021-10-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211022_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('Aproved', 'Aproved'), ('Reject', 'Reject')], max_length=50, null=True),
        ),
    ]
