# Generated by Django 3.2.8 on 2021-10-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='cus_id',
            field=models.AutoField(default=12, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
