# Generated by Django 3.2.8 on 2021-10-27 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211027_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='users',
        ),
    ]
