# Generated by Django 3.2.8 on 2021-11-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_goldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(default=1, upload_to='customer/image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='ornament_pic',
            field=models.ImageField(default='', upload_to='ornament_pic/image/'),
            preserve_default=False,
        ),
    ]
