# Generated by Django 3.2.8 on 2021-10-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customer_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ornament_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
