# Generated by Django 3.2.8 on 2021-10-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_customer_ornament_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(blank=True, null=True, upload_to='customer/image'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ornament_pic',
            field=models.ImageField(blank=True, null=True, upload_to='ornament_pic/image'),
        ),
    ]
